Feature/heat index worksheets
adhocteam/a11y-snippets pull request #6
Opened 2018-02-20 22:50 UTC by 1Copenut

### TODO: Verify the Word doc is accessible on Windows machine when approved

2018-02-28 22:25 UTC, dannychapman commented on worksheets/Accessibility Evaluation Checklist.md
> +User interface and experience designers, researchers, and front-end engineers are the primary audience. However, this is not an exhaustive list. Anyone with access to a web browser or mobile device c
'user experience designers'

2018-02-28 22:28 UTC, dannychapman commented on worksheets/Accessibility Evaluation Checklist.md
> +Keyboard testing is mostly a manual process. All pages under test should be free of errors identified by axe-core or other automated scanner first, then manual testing and ideally keyboard end-to-end
`or other automated scanner**s**`

2018-02-28 22:28 UTC, dannychapman commented on worksheets/Accessibility Evaluation Checklist.md
> +### Step 2. Audit with screen readers - maximal importance
Maximum

2018-02-28 22:29 UTC, dannychapman commented on worksheets/Accessibility Evaluation Checklist.md
> +### Step 3. Audit keyboard navigation - maximal importance
maximum

2018-02-28 22:33 UTC, dannychapman commented on worksheets/Accessibility Manual Testing Criteria.md
> +## Screen readers - 5 or more errors
consider writing out as five

2018-02-28 22:43 UTC, dannychapman commented
It would be great to add some guidelines as to what a good achievable score is, both to the readme and the spreadsheets.

2018-02-28 22:45 UTC, dannychapman commented on worksheets/Accessibility Manual Testing Criteria.md
> +## Screen readers - 5 or more errors
I realize there is pass/fail criteria, but setting something some baseline ideas as to what a typical starting score might be would be helpful.

2018-02-28 22:45 UTC, dannychapman commented
@1Copenut Made some minor line comments but otherwise this looks good.

2018-02-28 22:46 UTC, dannychapman requested changes
See comments, otherwise looks good.

2018-03-01 21:23 UTC, 1Copenut commented
@dannychapman All changes are in. I added a set of scores to the README and worksheets, that are goals to work toward. The manual errors tend to magnify scores greatly, so the algorithm may need tweaking, but it's a good first step.

2018-04-05 19:19 UTC, dannychapman approved these changes

2018-04-05 19:21 UTC, merged